### ISSUE TITLE
Release 0.4.0 binaries format

### ISSUE THREAD

**Issue by gpie3k** [adamrodger/gcloud-ctx#27]
Why tag.gz.zip?

**Comment by adamrodger** [comment]
Ah, not sure what's happened there. That seems to only affect v0.4.0 because earlier versions have the correct extensions.

Even stranger, the artifacts on the GitHub Action that's supposed to generate the release are correct as well, so I'm not sure how that's happened. I'll replace them with the correct ones.

**Comment by adamrodger** [comment]
OK, that's fixed 👍 The binaries on the 0.4.0 release are now correct.

Sorry about that, it won't happen in the next release.
